# Generated by Django 4.2.11 on 2024-11-11 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webprincipal', '0015_ordene_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdeneProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webprincipal.ordene')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webprincipal.productos')),
            ],
        ),
    ]
