# Generated by Django 4.2.11 on 2024-10-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('tp_usu', models.CharField(choices=[('ADMIN', 'Administrador'), ('USER', 'Usuario'), ('GUEST', 'Invitado'), ('MODERATOR', 'Moderador')], default='USER', max_length=10)),
            ],
        ),
    ]
