# Generated by Django 4.2.11 on 2024-10-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniusuario', '0002_usuario_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tp_usu',
            field=models.CharField(max_length=20),
        ),
    ]
