# Generated by Django 4.2.11 on 2024-10-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniusuario', '0003_alter_usuario_tp_usu'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_usu',
            field=models.CharField(default=2355, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=5456, max_length=20),
            preserve_default=False,
        ),
    ]
