# Generated by Django 4.2.11 on 2024-10-06 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniusuario', '0004_usuario_apellido_usuario_nombre_usu_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
