# Generated by Django 4.2.11 on 2024-10-18 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iniusuario', '0009_tipo_datosusuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='nombre_usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
