# Generated by Django 4.2.11 on 2024-10-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iniusuario', '0011_alter_datosusuario_nombre_usu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosusuario',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
