# Generated by Django 4.2.11 on 2024-11-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniusuario', '0012_remove_datosusuario_tipo_delete_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=12),
        ),
    ]
